trigger:
- main

pool:
  name: 'batch11'

steps:
- checkout: self
  fetchDepth: 0

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonarqubeconnection'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=devops_login
      sonar.projectName=devops_login

- task: Maven@4
  inputs:
    mavenPomFile: 'devops_login/pom.xml'
    goals: 'clean verify sonar:sonar'
    options: '-X -e' 
    publishJUnitResults: true

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'devops_login/target'
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
