trigger: none

pool:
  name: 'batch11'

steps:
# 1. Prepare SonarQube Analysis
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonarqubeconnection'   # service connection name
    scannerMode: 'Other'
    configMode: 'manual'
    cliProjectKey: 'devops_login'
    cliProjectName: 'devops_login'
    cliSources: 'devops_login'

# 2. Run Maven build + Sonar scan
- task: Maven@4
  inputs:
    mavenPomFile: 'devops_login/pom.xml'
    goals: 'clean verify sonar:sonar'
    publishJUnitResults: true

# 3. Publish SonarQube Quality Gate Result
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

# 4. Copy WAR to staging
- task: CopyFiles@2
  inputs:
    SourceFolder: 'devops_login/target'
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# 5. Publish WAR as artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
