---
- name: Deploy WAR to Tomcat
  hosts: local
  become: yes
  vars:
    war_source: "/var/lib/jenkins/workspace/pipeline/devops_login/target/devops_login-0.0.1-SNAPSHOT.war"
    tomcat_webapps: "/home/arshad/tomcat1/apache-tomcat-9.0.105/webapps/"
  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ war_source }}"
        dest: "{{ tomcat_webapps }}/"
        mode: 0644

    - name: Make Tomcat scripts executable
      file:
        path: "/home/arshad/tomcat1/apache-tomcat-9.0.105/bin/{{ item }}"
        mode: '0755'
      loop:
        - startup.sh
        - shutdown.sh

    - name: Stop Tomcat (if running)
      shell: "/home/arshad/tomcat1/apache-tomcat-9.0.105/bin/shutdown.sh"
      ignore_errors: yes

    - name: Start Tomcat
      shell: "/home/arshad/tomcat1/apache-tomcat-9.0.105/bin/startup.sh"
